services:
  # Discord Bot Service
  - type: web
    name: ssads-discord-bot
    env: docker
    rootDir: citizen-scoring-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: BASE_MESSAGE_POINTS
        value: 1
      - key: QUALITY_MESSAGE_MULTIPLIER
        value: 2
      - key: REACTION_BONUS_THRESHOLD
        value: 3
      - key: VOICE_CHANNEL_POINTS_PER_MINUTE
        value: 0.5
      - key: SPAM_PENALTY
        value: -5
      - key: GHOST_VOICE_PENALTY
        value: -2
      - key: REPORT_PENALTY
        value: -10
      - key: LEAK_PENALTY
        value: -50
    # These will be set manually in Render dashboard
    secretEnvVars:
      - key: DISCORD_TOKEN
        name: discord-token
      - key: DISCORD_CLIENT_ID
        name: discord-client-id
      - key: DATABASE_URL
        name: database-url

databases:
  # PostgreSQL Database
  - name: ssads-discord-bot-db
    databaseName: citizen_scoring
    user: ssads_user