[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
LOG_LEVEL = "info"
BASE_MESSAGE_POINTS = "1"
QUALITY_MESSAGE_MULTIPLIER = "2"
REACTION_BONUS_THRESHOLD = "3"
VOICE_CHANNEL_POINTS_PER_MINUTE = "0.5"
SPAM_PENALTY = "-5"
GHOST_VOICE_PENALTY = "-2"
REPORT_PENALTY = "-10"
LEAK_PENALTY = "-50"